### ISSUE TITLE
Problem about GDI GTK

### ISSUE THREAD

**Issue by Dadaist-chn** [lagadic/visp#1033]
I have installed Windows11 and Windows 10 SDK.(via VS code installer) But the Cmakelist of Visp cannot find the GUI. My operating system is windows11. Can you help me?

**Comment by fspindle** [comment]
Right know our IT team doesn't deploy Windows 11.
I will try to overcome that.
In the mean time, you should investigate the content of `cmake/FindGDI.cmake` adding some cmake messages to see where it fails to detect GDI.

**Comment by fspindle** [comment]
GDI is supported by ViSP on Win11: [tutorial](https://visp-doc.inria.fr/doxygen/visp-daily/tutorial-install-win11-msvc17.html)
