### ISSUE TITLE
 fatal error: visp3/io/vpImageStorageWorker.h: No such file or directory

### ISSUE THREAD

**Issue by arjunskumar** [lagadic/visp#1036]
I was trying to run tutorial-grabber example and the mentioned error pops up.

**Comment by fspindle** [comment]
`vpImageStorageWorker.h` was introduced in ViSP 3.4.0 release.
Your error means that you are using an older release.

**Comment by arjunskumar** [comment]
@fspindle I used 3.4.0 version only, later I uninstalled and used visp-ros module which was working good for me.
