### ISSUE TITLE
vpMomentAlpha: Question about symmetric judgement based on centered moments

### ISSUE THREAD

**Issue by xoox** [lagadic/visp#105]
in [modules/core/src/tracking/moments/vpMomentAlpha.cpp](https://github.com/lagadic/visp/blob/master/modules/core/src/tracking/moments/vpMomentAlpha.cpp)
line 62
```cpp
for (std::vector<double>::iterator it = ref_.begin(); it!=ref_.end(); ++it)
    if (*it<=1e-4)
      symmetric = true;
```
Since moments are negative sometimes, is it right Line 63 `if (*it<=1e-4)` be changed to `if (abs(*it)<=1e-4)`?

## Another Question

in `modules/core/include/visp3/core/vpMomentAlpha.h` [Line 123](https://github.com/lagadic/visp/blob/master/modules/core/include/visp3/core/vpMomentAlpha.h#L123) says:
```cpp
  //the order of values in the vector must be as follows:
  //mu30 mu21 mu12 mu03
```

But in `modules/core/src/tracking/moments/vpMomentAlpha.cpp` [Line 56](https://github.com/lagadic/visp/blob/master/modules/core/src/tracking/moments/vpMomentAlpha.cpp#L56) documented as following:
```cpp
...the reference alpha in the following order: \f$\mu_{03},\mu_{12},\mu_{21},\mu_{30}\f$.
```

So which one is correct?

**Comment by manisoftwartist** [comment]
Perhaps. If you created this suspecting the problem in #104, it has no relation. I have verified.

**Comment by xoox** [comment]
Right. This issue is not related to #104 
I'm not familiar with theories, But this line of code seems not be the right way.

**Comment by fspindle** [comment]
[Line 63](https://github.com/lagadic/visp/blob/master/modules/core/src/tracking/moments/vpMomentAlpha.cpp#L63) should be as:

    if (std::fabs(*it)<=1e-4)

and [Line 56](https://github.com/lagadic/visp/blob/master/modules/core/src/tracking/moments/vpMomentAlpha.cpp#L56) should be 

    \f$\mu_{30},\mu_{21},\mu_{12},\mu_{03}\f$

@manisoftwartist Could you confirm ? Thanks

**Comment by manisoftwartist** [comment]
Yes. seems fine for std::abs(). In line 56, the order of the moments should not matter.
