### ISSUE TITLE
problem about :change the control mode from stop to velocity control

### ISSUE THREAD

**Issue by 867415148** [lagadic/visp#1109]
I follow the tutorial：IBVS with a robot from Universal robot，try to complete  visual servo.  
When I run this command： ./servoUniversalRobotsIBVS --eMc ../../tutorial/calibration/ur_eMc.yaml --plot。 My UR5  moves to a certain position，then the  system prompts me：change the control mode from stop to velocity control。After that, my UR5 has no reaction.
Before I run this command，everthing is ok。
The system prompt is as shown in the figure。
The pose of UR5 after moving to the certain position is shown in the figure.
How can I solve this problem？ Help!!!!!!!!
![937a1a8a7467ca5d98a8f395ed8d5fe](https://user-images.githubusercontent.com/111264269/195758665-eab38307-c029-423a-a57f-7d5bde8bac9e.jpg)
![5abebfc8c44a4b8d79e7e64e7c4e37e](https://user-images.githubusercontent.com/111264269/195758806-87555748-7f8a-4c41-92e2-a593e5738f9d.jpg)

**Comment by fspindle** [comment]
The msg `Change the control mode from stop to velocity control` is just here to warn the user that the robot will be controlled in velocity.

The `servoUniversalRobotsIBVS` binary should open a windows that is displaying the image acquired by the Realsense camera. The robot can then only move if the apriltag is detected in the image and if the user enables the controller by a left click in the image.

**Comment by 867415148** [comment]
Thank you so much. I completed this experiment, and the effect is very good.Thank you again for your contribution and guidance.
