### ISSUE TITLE
vpColor doesn't work in mb-hybrid

### ISSUE THREAD

**Issue by MUSAZOU** [lagadic/visp#111]
I pulled and compiled the master branch, and run the mb-hybrid tutorial. the displayed image, model and texts are all black, no matter what color set.

![mb-hybrid](https://cloud.githubusercontent.com/assets/15811636/21079913/a37c6542-bfdb-11e6-82b1-9e56723a5ff8.JPG)

**Comment by fspindle** [comment]
Thanks for the feedback, there is an issue with vpDisplayOpenCV that doesn't use the rigth colors.
