### ISSUE TITLE
Construction of visual servo simulation platform

### ISSUE THREAD

**Issue by 867415148** [lagadic/visp#1113]
Hello, I have read this paper “Dynamic Identification of the Franka Emika Panda Robot with Retrieval of Feasible Parameters Using Penalty-Based Optimization”and have the following questions:

1、We found that the Franka Emika Panda manipulator was simulated in VREP simulation software in this paper. Now we want to conduct IBVS simulation experiments on UR5 manipulator in VREP software. Does the VISP library have corresponding tutorials or libraries containing C++classes to facilitate us to control UR5 in VREP?

2.At present, we have installed VISP separately and successfully run the IBVS tutorial on UR5. Next, we plan to install VISP-ROS and vision-Visp, do we need to delete the original VISP library and reinstall it in the order of VISP, VISP-ROS, and vision-VISP? Or can I continue to install VISP-ROS and vision-VISP based on the existing installation?

I really appreciate your help.

**Comment by fspindle** [comment]
1. Sorry there is no plan to do the same work with UR5 and VREP
2. No, keep ViSP installed from source and build visp_ros and vision_visp using existing ViSP installation. If ViSP is not found by ROS, set VISP_DIR var to the location of your visp-build folder
