### ISSUE TITLE
vpPose: Possible ambiguity or misunderstanding in doxygen message

### ISSUE THREAD

**Issue by xoox** [lagadic/visp#112]
in `modules/vision/src/pose-estimation/vpPose.cpp` [Line 147](https://github.com/lagadic/visp/blob/master/modules/vision/src/pose-estimation/vpPose.cpp#L147)
```
  \warning Considering a point from the class vpPoint, X, Y, and Z will
```

It's really mean oX, oY and oZ of class vpPoint, right? which is 3D information in the object frame.

Line 147 and 148 message would be better if clarified like following.
```
  \warning Considering a point from the class vpPoint, oX, oY, and oZ will
represent the 3D information in the object frame and x and y its 2D information.
```

**Comment by fspindle** [comment]
You are completly right. I will do the changes.
