### ISSUE TITLE
Dll not found after reinstallation of VISP - visp_io351.dll not found

### ISSUE THREAD

**Issue by VarnL0** [lagadic/visp#1127]
I have an error right after the installation of Visp and dataset, when I try to run the first example with displayGDI.exe I end up with this error :

visp_io351.dll not found. Reinstalling the program can help to solve this problem.

I reinstalled the program and the dataset but I end up with the exact same error at the same moment even though the installation worked perfectly.

Also the dll file is existing, could it help to move it to another directory ?
<img width="302" alt="image" src="https://user-images.githubusercontent.com/98879616/219348774-0171d2b8-6112-40be-81ce-bdc351d0f888.png">
<img width="721" alt="image" src="https://user-images.githubusercontent.com/98879616/219348949-2a684ba5-53b0-4e42-bfe0-99a598eb085d.png">

**Comment by fspindle** [comment]
You forgot to add the location of ViSP DLL in your path env var as explained in the [tutorial](https://visp-doc.inria.fr/doxygen/visp-daily/tutorial-install-win10-msvc17.html#install_win10_msvc17_env_var)

In your case you should add `C:\visp-ws-premier-essai\visp-build-vc17\install\x64\vc17\bin`

**Comment by VarnL0** [comment]
I actually added the location as mentionned in the tutorial, the problem is maybe coming from something else...
<img width="376" alt="image" src="https://user-images.githubusercontent.com/98879616/219422321-67bfb45a-cdf7-4df2-b0dc-84bdb469917c.png">

**Comment by fspindle** [comment]
You have to open a fresh cmd Windows after changing the env var.

**Comment by VarnL0** [comment]
Oh yes thank you  now everything works fine !
