### ISSUE TITLE
vpMomentAlpha: wrong abs() function using

### ISSUE THREAD

**Issue by xoox** [lagadic/visp#114]
In [vpMomentAlpha.cpp Line 130](https://github.com/lagadic/visp/blob/master/modules/core/src/tracking/moments/vpMomentAlpha.cpp#L130) and [Line 133](https://github.com/lagadic/visp/blob/master/modules/core/src/tracking/moments/vpMomentAlpha.cpp#L133),
there are three std::abs() functions are used. Here we are operating double numbers. So fabs() should be used.

**Comment by fspindle** [comment]
Thanks.
This issue occurs also in vpMomentCInvariant.cpp and vpMomentObject.cpp
