### ISSUE TITLE
Build failed with clang/llvm

### ISSUE THREAD

**Issue by xoox** [lagadic/visp#120]
Have you ever built with clang?
My building host is ubuntu 12.04 i686, clang-3.4
with `CC=clang` and `CXX=clang++`

Compiling failed with error in `/modules/sensor/src/framegrabber/flycapture/vpFlyCaptureGrabber.cp
p`

Error message:
```
/modules/sensor/src/framegrabber/flycapture/vpFlyCaptureGrabber.cp
p:986:77: error:
      cannot pass object of non-POD type 'FlyCapture2::PGRGuid' through variadic
      constructor; call will abort at runtime [-Wnon-pod-varargs]
  ..."Cannot start capture for camera with guid 0x%lx", m_guid));
```

**Comment by fspindle** [comment]
Builds with clang 3.5: https://travis-ci.org/lagadic/visp.
I will check with 3.4
