### ISSUE TITLE
Does Visp has an example for simulating eye-to-hand visual servo?

### ISSUE THREAD

**Issue by Steven-ZY** [lagadic/visp#1241]
Does Visp has an example for simulating eye-to-hand visual servo?

**Comment by fspindle** [comment]
I don't think so.

There is this example [servoAfma6Points2DCamVelocityEyeToHand.cpp](https://github.com/lagadic/visp/blob/master/example/servo-afma6/servoAfma6Points2DCamVelocityEyeToHand.cpp)  implemented on a real robot  from which you can get inspiration.
