### ISSUE TITLE
Some doubts about the LAGRANGE method to estimate the pose from points. 

### ISSUE THREAD

**Issue by 867415148** [lagadic/visp#1295]
Hello, I recently found the code for the Lagrangian method for solving the position from a point (From poseLagrangeNonPlan()) when I was learning about position estimation algorithms. I am unable to understand the formulas represented by these codes, can you please recommend me some papers to help me understand the Lagrangian method codes or briefly explain the principles of the codes. Thank you very much and have a nice life. @fspindle

**Comment by chaumett** [comment]
This method for pose estimation from N points comes from the very old calibration method by Faugeras & Toscani. It is explained on page 152 of this document (in french, sorry): http://rainbow-doc.irisa.fr/pdf/1990_these_chaumette.pdf
