### ISSUE TITLE
librealsense file rs-capture not found and problems with svn export

### ISSUE THREAD

**Issue by shrutichakraborty** [lagadic/visp#1317]
hello I have two issues: 

First, I have cloned librealsense and build the files. But the ./examples/capture/rs-capture file cannot be found.

Secondly, in order to do hand eye calibration I'm following the tutorial on https://visp-doc.inria.fr/doxygen/visp-daily/tutorial-calibration-extrinsic.html but svn export https://github.com/lagadic/visp.git/trunk/apps/calibration des not work and the error I get is as follows : 

![Screenshot from 2024-01-25 17-30-41](https://github.com/lagadic/visp/assets/150450346/011780eb-0b08-4cb3-bd98-ecd80fd4e9f2)

Any ideas why these are happening will be very appreciated! 

Thank you!

**Comment by fspindle** [comment]
It seems that github doesn't allow anymore this way to access to the repo.
The only simple way I see is to clone https://github.com/lagadic/visp and copy the `apps/calibration` folder
