### ISSUE TITLE
buildFrom methods return a copy instead of a reference or void

### ISSUE THREAD

**Issue by SamFlt** [lagadic/visp#1353]
Many classes in ViSP have a standard buildFrom method, which serves as a delayed constructor/initializer.

In many classes, this method has the signature `vpObject buildFrom(Args... args)`. However, buildFrom modifies the calling object and there is very little sense in returning a copy.

This method should either:
 - Return void: this method acts as a setter
 - Return a reference: Allows for method chaining e.g. x.buildFrom(args).compute();

Currently, we can perform method chaining, but this is misleading

Some of the affected classes are:
- `vpRzyxVector`, `vpRxyzVector`, `vpRzyzVector`
- `vpThetaUVector`
- `vpQuaternionVector`
- `vpRotationMatrix`
- `vpTranslationVector`
- `vpPoseVector`
- `vpVelocityTwistMatrix`
- `vpForceTwistMatrix`

**Comment by fspindle** [comment]
We could make all the `buildFrom()` deprecated and introduce new functions `vpObject &build(Args... args)`

**Comment by rolalaro** [comment]
@fspindle I like the idea ! If you want, I can do a PR for that ?

**Comment by fspindle** [comment]
@rolalaro Yes, it would be great

**Comment by rolalaro** [comment]
The problem was addressed in PR #1406 .
