### ISSUE TITLE
ViSP-third-party.txt not showing 3rd party Realsense2: Yes.

### ISSUE THREAD

**Issue by minku1219** [lagadic/visp#1364]
librealsense is already installed, still visp is not able to detect librealsense2 as package.

Just to confirm the package, i ran the command 
```
locate librealsense2.so
```
## output:-
/usr/lib/x86_64-linux-gnu/librealsense2.so.2.54
/usr/lib/x86_64-linux-gnu/librealsense2.so.2.54.2

Also i have followed the installation for visp properly.

I am able to get the output for the following file :- testUniversalRobotsGetData

**Comment by fspindle** [comment]
What is the result of

```
$ sudo updatedb
$ locate librealsense2/rs.hpp
```

You need also cxx standard set to 11 at least

**Comment by minku1219** [comment]
Should i export the path for REALSENSE2_INCLUDE_DIRS ?

**Comment by fspindle** [comment]
There is something strange having the library in `/usr/lib` and the headers in `/opt/ros`. 

Can you again run
```
$ sudo updatedb
$ locate librealsense2.so
```

**Comment by minku1219** [comment]
Can you suggest some quick resolutions?

**Comment by minku1219** [comment]
I removed the ros installation related to librealsense and did a fresh installation for librealsense2 from official package.
Now the headed rs.hpp is also not being shown.

**Comment by fspindle** [comment]
As you did removing the ros package is what I would suggest.
Did you install the official package with `apt install librealsense2-dev`?

**Comment by minku1219** [comment]
Hi, Thanks for your valuable feedbacks. Perhaps, i have solved the issue after cleaning the librealsense installation completely and reinstalling it.
