### ISSUE TITLE
Create a tutorial that shows how to load, display and modify an image

### ISSUE THREAD

**Issue by fspindle** [lagadic/visp#140]
The image modification could be just the conversion to a gray level image from a color image. Other ideas are also welcome.

**Comment by sudoankit** [comment]
Visp is pretty interesting! I'll work on this to start my contributions!

**Comment by yshkp** [comment]
Working on it and planning for the modification of image by distinctly adjusting its RGB values. Any ideas regarding this how to process ?

**Comment by yshkp** [comment]
Yes Sure, will start working on it and I am also looking to contribute in a
project through GSOC 2019 as i have keen interest towards Computer Vision
and VIsp offers really easy and impressive platform to nourish skills and
perform at higher level.

**Comment by fspindle** [comment]
Today there are already these [image processing tutorials](https://visp-doc.inria.fr/doxygen/visp-daily/tutorial_imgproc.html) that address this enhancement.
