### ISSUE TITLE
Create a tutorial using ViSP with Eclipse

### ISSUE THREAD

**Issue by fspindle** [lagadic/visp#142]
It should show how to import ViSP in Eclipse IDE.

**Comment by Lrakulka** [comment]
I'm on it.

**Comment by fspindle** [comment]
Perfect thanks.

I would be interested to introduce your tutorial as all the existing that are in the [doc](https://github.com/lagadic/visp/tree/master/doc) folder and generated using Doxygen. It will allow us to make it evolve easily

**Comment by fspindle** [comment]
Closed by PR #150 and #158
