### ISSUE TITLE
Create a tutorial saving images from a stream

### ISSUE THREAD

**Issue by fspindle** [lagadic/visp#144]
It should explain how to save an image sequence from a video stream acquired by a camera.

**Comment by yurriy** [comment]
I'll do it

**Comment by fspindle** [comment]
Welcome

**Comment by yurriy** [comment]
@fspindle,
there already exists tutorial-video-recorder.cpp. Should the tutorial just explain it, or there must be something new?

**Comment by fspindle** [comment]
This new tutorial could be referenced in [Tutorial: Image frame grabbing](http://visp-doc.inria.fr/doxygen/visp-daily/tutorial-grabber.html) in the [next section](http://visp-doc.inria.fr/doxygen/visp-daily/tutorial-grabber.html#grabber-next).

It should explain tutorial-video-recorder.cpp that is a good starting and any else other useful things that you think that could be useful for beginners.

Feel also free to add new cpp if you think it could help.

**Comment by yshkp** [comment]
@fspindle  Section already includes its explanation. Do you want brief of code working ? Then I can look into it.

**Comment by fspindle** [comment]
@yshkp The [Tutorial: Image frame grabbing](http://visp-doc.inria.fr/doxygen/visp-daily/tutorial-grabber.html) already answer this enhancement. I will close it.
