### ISSUE TITLE
Improve video reader to determine the first and last image of a sequence of images

### ISSUE THREAD

**Issue by fspindle** [lagadic/visp#145]
The [video reader class](http://visp-doc.inria.fr/doxygen/visp-daily/classvpVideoReader.html) should be improved to determine the first and last image of a sequence efficently.

Let us consider a folder with images ``image%04d.png`` where the first image is ``image2000.png`` and the last ``image2345.png`` the class should be able to determine that the first image has number 2000 and the last 2345.

**Comment by shaunakdixit** [comment]
sir
I would like to work upon this 
since I had gone through all the tutorials.
Maybe I can solve this one.

**Comment by yurriy** [comment]
Hi, @shaunakdixit
Do you want to do it for Windows and Unix both? I can make OS-dependent part, if you're not against.

**Comment by shaunakdixit** [comment]
Hi, @yurriy sure you can go forward.
Although due to exams I can not work on it for 2-3 days.

**Comment by shaunakdixit** [comment]
hi, @fspindle 
Sir, I was implementing a new function of class vpVideoReader in an example.
but it is showing an error "has no member new_function()".
although I have built the visp again after implementing the new function in vpVideoReader.h and vpVideoReader.cpp

**Comment by fspindle** [comment]
Already done
