### ISSUE TITLE
Can you please provide the cpp and Cmakelists files for the example, thank you very much!

### ISSUE THREAD

**Issue by jxx0350** [lagadic/visp#1484]
![Snipaste_2024-10-18_16-07-33](https://github.com/user-attachments/assets/8ae94b4c-2e08-4a23-87a2-ee7bc57f5017)

**Comment by fspindle** [comment]
If you had taken the time to do some research, you would have found this example [here](https://github.com/lagadic/visp/blob/master/modules/core/test/camera/catchJsonCamera.cpp).

There is the ViSP getting started [tutorial](https://visp-doc.inria.fr/doxygen/visp-daily/tutorial-getting-started.html) that gives an example of a `CMakeLists.txt` file using ViSP.
