### ISSUE TITLE
Improve vpVideoReader to introduce a frame step

### ISSUE THREAD

**Issue by fspindle** [lagadic/visp#155]
vpVideoReader class uses a constant frame step equal to 1, meaning that the next frame number to open is equal to the current frame number + 1.

It would be nice to introduce a new function ``setFrameStep()`` that allows the user to set the frame step. 

Up to now, vpVideoReader cannot handle the following sequence of images: ``image10.png``, ``image20.png``, ``image30.png``. Introducing ``setFrameStep(10)`` could solve this issue.

As done in #151 it could be nice to go further and determine automatically the frame step of a sequence to be able to handle automatically a sequence without calling ``setFrameStep()``

**Comment by Lrakulka** [comment]
I want to work on it.

**Comment by fspindle** [comment]
Welcome

**Comment by Lrakulka** [comment]
I have a question.
What should return the method `findLastFrameIndex()` after my improvements?
Example:
We have a sequence of frames: 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16
We set `setFrameStep()` to 5
We call the method `findLastFrameIndex()`
What should return the method? (last index = 15 or 16)

**Comment by fspindle** [comment]
`findLastFrameIndex()` don't have to be changed in this enhancement since it will be the result of PR #151 .
To answer your question `findLastFrameIndex()` will return 16.

**Comment by Lrakulka** [comment]
#167
