### ISSUE TITLE
Bug in line 124 of VISPConfig.cmake

### ISSUE THREAD

**Issue by abhineet123** [lagadic/visp#177]
There is a bug in line 124 of cmake/VISPConfig.cmake which should be:

` elseif(VISP_STATIC AND EXISTS "${VISP_CONFIG_PATH}/${VISP_ARCH}/${VISP_RUNTIME}/lib/VISPConfig.cmake")`

instead of

` elseif(VISP_STATIC EXISTS "${VISP_CONFIG_PATH}/${VISP_ARCH}/${VISP_RUNTIME}/lib/VISPConfig.cmake")`

which it currently is.

**Comment by fspindle** [comment]
Thanks for your feedback
