### ISSUE TITLE
Request for Hadamard product

### ISSUE THREAD

**Issue by amagasso** [lagadic/visp#189]
Hi,
I would like to request the element-wise matrix product also known as [hadamard product](https://en.wikipedia.org/wiki/Hadamard_product_(matrices)). 
Aly

**Comment by fspindle** [comment]
What is the size of the matrices you are manipulating ?

**Comment by amagasso** [comment]
It depends. I have several matrices of moderate size  (180*6, 360*6 or 180*360) that I use for convolution calculus. I think that it is a function that can be useful in Visp. For now I am using [itpp](http://itpp.sourceforge.net/4.3.1/classitpp_1_1Mat.html#a0938b93b523ffdfcfb1788052f1905be) for this kind of operation.
