### ISSUE TITLE
Matrix multiplication enhancement suggestion

### ISSUE THREAD

**Issue by amagasso** [lagadic/visp#190]
Hi,
Maybe for large matrix we could consider using a BLAS library like Lapack to perform matrices multiplication?
Of course, we will have to test if the performance is improved or not.

**Comment by fspindle** [comment]
In your use case, what is the size of your large matrices ?

**Comment by s-trinh** [comment]
In my opinion, with interaction matrix like size (`Nx6`), the current implementation could be enough.
But for general use and with large matrix, [BLAS library](https://stackoverflow.com/questions/1303182/how-does-blas-get-such-extreme-performance) should be more efficient.
One issue I see is maybe the overhead time to convert back and forth the data matrix, if any.
This could be a possible future enhancement (validated by proper benchmarks).
