### ISSUE TITLE
How to update the package to visp3.1 in ROS

### ISSUE THREAD

**Issue by TokyoClod** [lagadic/visp#262]
The version of visp now in ROS is 3.0.1, I installed using `sudo apt-get install ros-kinetic-visp`,i am wondering how can i update it to the up-to-date version of 3.1.0 for the AprilTag integration.
Or could anyone tell me how to install it from source?

**Comment by fspindle** [comment]
This is possible removing all `ros-kinetic-visp`, `ros-kinetic-vision-visp`, `ros-kinetic-visp_...` packages and installing them from source:

1. For ViSP follow this [tutorial](http://visp-doc.inria.fr/doxygen/visp-daily/tutorial-install-ubuntu.html)

2. For `vision_visp` and other `visp_...` packages, install from source

````
$ cd ~/catkin_ws/src
$ git clone https://github.com/lagadic/vision_visp.git
$ cd ..
$ catkin_make -j4 -DVISP_DIR=~/workspace/visp/visp-build
````
