### ISSUE TITLE
Eye-to-hand visual servo using kinect2

### ISSUE THREAD

**Issue by jch007** [lagadic/visp#274]
（1）Can I use kinect2 to help me finish the visual servo in Eye-to-hand case?(A kinect2 is not attached to hand）

（2）The tutorial support kinect1,if I want to use kinect2,what should I do？just change the kinect driver version from libfreenect to libfreenect2?

**Comment by fspindle** [comment]
Since we don't have Kinect2 in the lab, this device is not supported.

But feel free to contribute with a PR. We would be very happy...
