### ISSUE TITLE
how much fps on ios and android?

### ISSUE THREAD

**Issue by 2017hack** [lagadic/visp#291]
i want to use it  on android and ios for app development， so very hopefully to get the reply! Thank you very much

**Comment by fspindle** [comment]
Depends on the ios device. ANdroid is not supported yet.

**Comment by 2017hack** [comment]
Thans a lot!  Have you tested the part of modelbase tracking, whether it is  at fps above 30, on above iphone S6?

**Comment by fspindle** [comment]
Not tested, sorry

**Comment by saiakash** [comment]
did you support on android?

**Comment by fspindle** [comment]
There are some [tutorials](https://visp-doc.inria.fr/doxygen/visp-daily/tutorial_android.html) for Android
