### ISSUE TITLE
How to convert a 3d model from STP file to BND file?

### ISSUE THREAD

**Issue by codetaobeibei** [lagadic/visp#292]
Hi,
I have a robot model with the file pattern .stp from Solidworks, I want to convert it to .bnd file which is used in vpScene.cpp demo. But I failed to convert it because of no commonly used tools I can find to do this work. So, could you please give some tips or share some methods about it?Thank you.

**Comment by fspindle** [comment]
I just make available [sld2bnd](https://github.com/lagadic/sld2bnd) project that allows to convert Solidworks `*.sld` files to `*.bnd` files compatible with the robot simulator in ViSP

**Comment by codetaobeibei** [comment]
Thank you very much for your kindly reply and sharing the project. It is very useful for me. I am trying the method you give, but a problem comes to me is that my Solidworks(version 2016) can not export `*.stp` files as `*.sld` files. Or do you mean `*.sldprt`? Could you please tell me which version of solidworks you are using? Thank you.

**Comment by fspindle** [comment]
I don't know. You should check if the content of your `*.sldprt` is similar to the sample files `*.sld` that are in ViSP robot module. 

The modeling of the Afma6 and Viper850 robot simulators was done by hand without Solidworks
