### ISSUE TITLE
The pose coordinate is fixed?

### ISSUE THREAD

**Issue by 2017hack** [lagadic/visp#296]
hi, i am very happy to try your visual servoing platform. i have a question about whether the vpTranslationVector's coordinate from pose calculated by vpMbEdgeKltTracker is millimeter fixedly?
when i use camera of different resolution, whether the result of vpMbEdgeKltTracker's track has   difference?

**Comment by fspindle** [comment]
ViSP uses International convention, translation in meter, rotation in rad.
Sure, using different camera resolutions will lead in different camera poses since the camera intrinsic parameters used to convert pixels to meter will differ.
