### ISSUE TITLE
Possible issue when comparing two vpRGBa.

### ISSUE THREAD

**Issue by s-trinh** [lagadic/visp#3]
Possible issue when comparing two vpRGBa.
The [current code](https://github.com/lagadic/visp/blob/master/modules/core/src/image/vpRGBa.cpp#L130) to test if two vpRGBa are different returns false when at least one channel is equal:
```
/*!
Compare two color pixels.
\return true if the images are different, false if they are the same.
*/
bool vpRGBa::operator!=(const vpRGBa &v)
{
  if (R == v.R)
    return false;
  if (G == v.G)
    return false;
  if (B == v.B)
    return false;
  if (A == v.A)
    return false;
  return true ;
}
```

So we could end up with situations where the two following tests will return false:
```
  vpRGBa rgba1(10, 20, 30), rgba2(10, 20, 40);
  std::cout << "rgba1==rgba2 ? " << (rgba1==rgba2) << std::endl;
  std::cout << "rgba1!=rgba2 ? " << (rgba1!=rgba2) << std::endl;
```

I will submit a pull request.

**Comment by fspindle** [comment]
Fixed with PR #4
