### ISSUE TITLE
Can I ask you about the camera model?

### ISSUE THREAD

**Issue by yongjiaPython** [lagadic/visp#325]
## Hello @fspindle, I want to build a virtual servoing platform. Camera model confused me.  So，Can you tell me the camera model used for the sample program experiment? Thank you for your help！

**Comment by fspindle** [comment]
The model is explained in this [tutorial](http://visp-doc.inria.fr/doxygen/visp-daily/tutorial-calibration-intrinsic.html)

In simulation, a good starting is to set u_0 = (image_width)  / 2 and v_0 = (image height) / 2. You can consider px = py = 600.

**Comment by yongjiaPython** [comment]
## Hello @fspindle，I want to know the camera brand, parameters, and type not the camera model. I want to buy a camera like your experiment used. Thank you for your help！
