### ISSUE TITLE
Re ask: Can I ask you about the camera brand, parameters and type?

### ISSUE THREAD

**Issue by yongjiaPython** [lagadic/visp#326]
Hello @fspindle，I want to know the camera brand, parameters and type not the camera model. I want to buy a camera like your experiment used. Thank you for your help！

**Comment by fspindle** [comment]
This not the right way to ask this kind of questions. Github issues are for ViSP issues, not for user questions/answers.

Use rather the [forum](https://gforge.inria.fr/forum/forum.php?forum_id=1295&group_id=397)
