### ISSUE TITLE
ViSP Contrib Module including non-existant vpConfig.h header 

### ISSUE THREAD

**Issue by jchevrie** [lagadic/visp#368]
At lines 709-711, in cmake/VISPModule.cmake : 
add `#include <visp3/module_name/vpConfig.h>` in case of `module_name` containing "core".

It appears for ustk_core, and produces non-existant include `#include <visp3/ustk_core/vpConfig.h>` in file visp_ustk_core.h

Possible solutions: 
1) replace `if(__name MATCHES "core")` by `if(__name EQUAL "core")`
   Potential problem with this solution : a config file (like usConfig.h in UsTK) won't be automatically included in the headers.
2) Add a new system to detect if a config file is associated to a contrib module and add this file to the headers.

**Comment by fspindle** [comment]
The solution that I implemented is:

1. Replace `if(__name MATCHES "core")` by `if(__name MATCHES "^core$")` to have the exact match

2. Improve `vp_add_config_file()` cmake macro to add the generated file to the module headers. See an example in ustk [core](https://github.com/lagadic/ustk/blob/master/modules/ustk_core/CMakeLists.txt#L47) module
