### ISSUE TITLE
Wrong urls in visp/doc/tutorial-calibration.doc

### ISSUE THREAD

**Issue by galou** [lagadic/visp#38]
The two urls for the calibration patterns are invalid.

**Comment by fspindle** [comment]
I just updated the web pages with the right link:
http://visp-doc.inria.fr/download/calib-grid/OpenCV_Chessboard.pdf
http://visp-doc.inria.fr/download/calib-grid/grid2d.pdf

**Comment by galou** [comment]
Great! Thanks for the quick reaction!
