### ISSUE TITLE
Warning when tracking through a live camera using v4l2

### ISSUE THREAD

**Issue by Ojaswi** [lagadic/visp#381]
Hi,

I get the following warning whenever I run _tutorial-klt-tracker-live-v4l2_ or _tutorial-apriltag-detector-live_ :

_Warning: cannot set input channel to 2_

What does this mean and how can I fix this? I am using ViSP 3.2.0 on Ubuntu 16.04.

**Comment by fspindle** [comment]
This is an internal message that is not critical.
It relates to the usage of the grabber with a BTTV video board. Since we never know if the user is using an usb camera or a BTTV board, the warning is printed in both cases.
