### ISSUE TITLE
Meaningless camera parameters when calibrating built-in auto-focusing camera

### ISSUE THREAD

**Issue by xoox** [lagadic/visp#382]
Hi, here is an archive of pictures which were taken with an Android pad's built-in camera with auto-focus on.
[CalibrationImages.zip](https://github.com/lagadic/visp/files/2122192/CalibrationImages.zip)
When calibrating with [camera_calibration.cpp](https://github.com/lagadic/visp/blob/master/example/calibration/camera_calibration.cpp), using configuration of following
```
BoardSize_Width: 8
BoardSize_Height: 6
Input: IMG_000000%02d.png
```
We got the following results.
```
Camera parameters for perspective projection without distortion:
  px = -88203.51854      py = -116077.7879
  u0 = 534.2792801       v0 = -7344.512771
Camera parameters for perspective projection with distortion:
  px = -156113.921       py = 0.0005820611166
  u0 = 337.497445        v0 = 469.8225272
  kud = 60255.8005
  kdu = -1.391628909e-11
```

Perhaps because of the actual camera parameters of each images are slightly different from each other, it makes ViSP giving out wrong calculated parameters. Where px and py should never be negative.

With the same set of images, we calibrated the camera parameters using OpenCV's [calibration.cpp](https://github.com/opencv/opencv/blob/master/samples/cpp/calibration.cpp). The results are more reasonable and useful as following.
```
px = 1590.0104461088167
py = 1590.0104461088167
u0 = 526.28984526994907
v0 = 697.72005855396390
kud = 0.49497071297669776
```
ViSP fails to perform calibration while OpenCV's calibration process seems more robust and usable.
It is more friendly that `vpCalibration::computeCalibrationMulti()` would return with failure status instead of meaningless parameters.
Or the calibration algorithms may need some improvements.

**Comment by xoox** [comment]
How rapid response.
The square size is the same as the example default which is 0.025

It would be better if the sanity check code were added to implementation of `int vpCalibration::computeCalibrationMulti()`. The return code of this function should be a none-zero value in the above case.

**Comment by fspindle** [comment]
I agree. I wil do the changes you propose.
