### ISSUE TITLE
vpCircle::display() didn't work as expected

### ISSUE THREAD

**Issue by liaoyeguo** [lagadic/visp#400]
according to this document  [http://visp-doc.inria.fr/manual/visp-tutorial-geometric-objects.pdf](url), vpCircle::display() method should draw a ellipse as follow
![image](https://user-images.githubusercontent.com/2355910/42722917-e1253238-8786-11e8-9637-89fdfebfddf0.png)

_image from visp-tutorial-geometric-objects.pdf_

However, when i build and run the example `example/manual/geometric-features/manGeometricFeatures.cpp`, the result didn't work as expected.

![image](https://user-images.githubusercontent.com/2355910/42722953-86e1259c-8787-11e8-819b-f52f7a7e9f83.png)

_display methods for other features are commented out._

What should I do to fix this problem ?

Currently,  I draw a ellipse by calling `vpMeterPixelConversion::convertEllipse` followed by `vpDisplay::displayEllipse`.
I was wondering if there exists a simple way to draw a projected circle?

**Comment by fspindle** [comment]
I don't know why the `vpCircle::display()` displays the circle as a cone.
I also notice that the behavior is similar for `vpSphere::display()`. I will propose a PR to modify the code.

In the mean time, I give below the complete code to display the 3D circle as expected:
````
    circle.display(I, cam, vpColor::orange); // draw an orange ellipse over I

    vpImagePoint center;
    double mu20, mu11, mu02;
    vpMeterPixelConversion::convertEllipse(cam, circle, center, mu20, mu11, mu02);
    vpDisplay::displayEllipse(I, center, mu20, mu11, mu02, true, vpColor::orange, 3);
````
