### ISSUE TITLE
vpRealSense2.cpp

### ISSUE THREAD

**Issue by Betancourt20** [lagadic/visp#416]
After doing 
$ cd $VISP_WS/visp-build
$ make -j4
I got this :
/home/unknown/visp-ws/visp-3.1.0/modules/sensor/src/rgb-depth/realsense/vpRealSense2.cpp: In member function ‘void vpRealSense2::acquire(unsigned char*, unsigned char*, std::vector<vpColVector>*, unsigned char*, rs2::align*)’:
/home/unknown/visp-ws/visp-3.1.0/modules/sensor/src/rgb-depth/realsense/vpRealSense2.cpp:98:22: error: ‘class rs2::align’ has no member named ‘proccess’
     data = align_to->proccess(data);
                      ^
What can I do?
Thanks in advance

**Comment by s-trinh** [comment]
This has been fixed in the ViSP master branch. You should clone the master branch instead of using ViSP 3.1.0.
