### ISSUE TITLE
Professional Edition Licensing

### ISSUE THREAD

**Issue by bergeltt** [lagadic/visp#420]
According to this page: http://visp.inria.fr/visp-license/ this library can be licensed for commercial use if GNU GPL v2 isn't able to be used with the commercial product.

I have contacted the creator of the library for information on licensing but I have received no response. Is it still possible to license this library for commercial use and not be bound by GNU GPL v2?

**Comment by fspindle** [comment]
Sorry for the delay.

Yes, this library could be licensed for commercial use.

Additional information is provided contacting the authors using visp@inria.fr
