### ISSUE TITLE
Please have one cmake variablefor DATADIR

### ISSUE THREAD

**Issue by yurivict** [lagadic/visp#424]
You hardcode this location in many places:
* https://github.com/lagadic/visp/blob/master/cmake/OgreTools.cmake#L318
* https://github.com/lagadic/visp/blob/master/cmake/OgreTools.cmake#L344
* https://github.com/lagadic/visp/blob/master/cmake/OgreTools.cmake#L351
* https://github.com/lagadic/visp/blob/master/cmake/VISPGenerateHeaders.cmake#L46
* https://github.com/lagadic/visp/blob/master/cmake/VISPGenerateHeaders.cmake#L65
* https://github.com/lagadic/visp/blob/master/cmake/VISPModule.cmake#L713

It should be in one place. I would also like to suggest to drop ```-${VISP_VERSION}``` from it, because only one version can be installed at a time.

**Comment by fspindle** [comment]
ok to introduce a variable for `${CMAKE_INSTALL_DATAROOTDIR}/visp-${VISP_VERSION}`

I can drop `-${VISP_VERSION}` hoping that there will be no side effect for debian multi-arch support.
