### ISSUE TITLE
vpRobotViper650 getPosition(vpRobot::REFERENCE_FRAME) error

### ISSUE THREAD

**Issue by rlagneau** [lagadic/visp#429]
Hello,

I am working at the INRIA Rennes.
When I tried to run the testRobotViper650-frames test, the program crashed on the line :
robot.getPosition(vpRobot::REFERENCE_FRAME, f_pose_t);
https://github.com/lagadic/visp/blob/7e8eb9970912d542d7ae97824eceb7feacf9fe52/modules/robot/test/servo-viper/testRobotViper650-frames.cpp#L170

The error message is "stack smashing detected". I don't have any clue of what can be the problem. Any idea ?

Regards

**Comment by fspindle** [comment]
This error occurs also with the Viper 850.
