### ISSUE TITLE
Memory leak in vpLinProg.cpp

### ISSUE THREAD

**Issue by fspindle** [lagadic/visp#449]
@oKermorgant [Continous integration](http://cdash.inria.fr/CDash/index.php?project=ViSP&date=2018-10-17) shows that sometimes `quadprog` and `quadprog_eq` examples return an exception:
```
$ ./quadprog -d
terminate called after throwing an instance of 'vpException'
  what():  Unable to extract column 20 from the 20x20 matrix
Abandon
```
This exception comes from `vpMatrix::getCol()` and is produced when the column that is asked is out of the matrix.

I think that this issue comes from line [L144](https://github.com/lagadic/visp/blob/master/modules/core/src/tools/optimization/vpLinProg.cpp#L144) or [L195](https://github.com/lagadic/visp/blob/master/modules/core/src/tools/optimization/vpLinProg.cpp#L195) where `j` could be equal to the number of columns returned by `getCols()`

**Comment by oKermorgant** [comment]
I cannot reproduce it on my version and think it is solved in this PR: https://github.com/lagadic/visp/pull/447
