### ISSUE TITLE
Java bindings for vpRowVector and vpColVector are wrong

### ISSUE THREAD

**Issue by fspindle** [lagadic/visp#457]
@AKS1996 I can't figure out how to fix incomplete bindings for some visp_core classes constructors that have vectors as arguments.

For example, in `core.inl.hpp` there is the function 
```
JNIEXPORT jlong JNICALL Java_org_visp_core_VpRowVector_VpRowVector_12
  (JNIEnv* env, jclass , jdoubleArray v)
{
  static const char method_name[] = "core::VpRowVector_12()";
  try {
    LOGD("%s", method_name);
    std::vector<double> v;
    vpRowVector* _retval_ = new vpRowVector( v );
    return (jlong) _retval_;
  } catch(const std::exception &e) {
    throwJavaException(env, &e, method_name);
  } catch (...) {
    throwJavaException(env, 0, method_name);
  }
  return 0;
}
```
that should be rather:
```
JNIEXPORT jlong JNICALL Java_org_visp_core_VpRowVector_VpRowVector_12
  (JNIEnv* env, jclass , jdoubleArray v)
{
  static const char method_name[] = "core::VpRowVector_12()";
  try {
    LOGD("%s", method_name);
    std::vector<double> v_ = List_to_vector_double(env, v);
    vpRowVector* _retval_ = new vpRowVector( v_ );
    return (jlong) _retval_;
  } catch(const std::exception &e) {
    throwJavaException(env, &e, method_name);
  } catch (...) {
    throwJavaException(env, 0, method_name);
  }
  return 0;
}
```

The same occur for `Java_org_visp_core_VpColVector_VpColVector_12`

For me changes have to be done in `gen_java.py` before [L1018](https://github.com/lagadic/visp/blob/master/modules/java/generator/gen_java.py#L1018) in order to set `c_prologue` to something similar to `std::vector<double> v_ = List_to_vector_double(env, v);` 

Should this be done near [L741](https://github.com/lagadic/visp/blob/master/modules/java/generator/gen_java.py#L741) ?

**Comment by AKS1996** [comment]
Refer [this file](https://github.com/lagadic/visp/blob/master/modules/java/generator/src/cpp/listconverters.cpp) for more

**Comment by fspindle** [comment]
Sorry, my initial post was sent before I finished. Now it is complete.
