### ISSUE TITLE
Extrinsic Calibration Failing

### ISSUE THREAD

**Issue by JadBatmobile** [lagadic/visp#471]
Hello All,

I have a setup with a parallel delta robot and a camera attached to the end affector looking downwards.
Using the kinematic equations of the delta robot, i am able to command it to different locations in XYZ.

I would like to perform the extrinsic calibration but the delta kinematics do not provide an orientation of the end affector, since there is none w.r.t to the base frame. When i provide as inputs the camera poses (which include orientation), and the delta poses (only translation, 0 on the orientation). This leads to the algorithms in ./tutorial-hand-eye-calibration not converging to a solution.

Any thoughts?

Thank you :)

**Comment by fspindle** [comment]
The implemented algorithm cannot handle this particular case (ie robot end effector without rotation wrt base frame).
We will try to find how we can modify the algorithm, but I'm unable to say right now when we will introduce it.

**Comment by JadBatmobile** [comment]
Certainly, thank you for your response. I am reading the paper released by HAL-Inria "Hand-eye calibration" https://hal.inria.fr/inria-00590039/document

With respect to this paper, can you correspond the functions called in the calibrate method in visp with the techniques mentioned in this paper?

Specifically, there are two approaces, R then t (R is solved for and then t is optimized for). Also, R and t (both are solved simultaneously through minimization or error functions).

I know R then t is implemented in visp, is R and t?

**Comment by fspindle** [comment]
If you have the curiosity to check what is implemented in [vpHandEyeCalibration::calibrate()](https://github.com/lagadic/visp/blob/master/modules/vision/src/calibration/vpHandEyeCalibration.cpp#L837) you will see that we first estimate the rotation, then the translation.

**Comment by JadBatmobile** [comment]
Yes i have looked, and i see the rotation then translation calculation. I just wanted to make sure i did not miss something.

Thank you sir

**Comment by JadBatmobile** [comment]
Do you have any thoughts on what direction should i proceed in to solve my particular issue?
