### ISSUE TITLE
can not install librealsense2 with visp

### ISSUE THREAD

**Issue by FreyGod** [lagadic/visp#472]
when I did not use realsense2, I can build and install visp successfully.
when I use librealsense2 and bulid visp,  vs2015 will show me errors like "LINK : fatal error LNK1181: can not open input file“..\..\x64\vc14\lib\Release\visp_robot310.lib”"
![_20181202154331](https://user-images.githubusercontent.com/35127407/49337123-1464dc80-f649-11e8-86bb-892c956636bd.png)

I have tried so many many many times!

**Comment by FreyGod** [comment]
I have use cpp11

**Comment by fspindle** [comment]
For my own curiosity, which was your issue ?

**Comment by FreyGod** [comment]
I have fixed the problem by downloading  source code from github rather than release version. Thank you so much.

郭飞

在 2018年12月3日，15:12，Fabien Spindler <notifications@github.com<mailto:notifications@github.com>> 写道：


For my own curiosity, which was your issue ?
