### ISSUE TITLE
Optimize vpImageTools::undistort()

### ISSUE THREAD

**Issue by fspindle** [lagadic/visp#490]
This function [vpImageTools::undistort()](https://visp-doc.inria.fr/doxygen/visp-daily/classvpImageTools.html#ac5ce18feb04a1311f6a085d81f125101) sounds very slow compared to OpenCV equivalent implemented in [cv::undistort()](https://docs.opencv.org/3.1.0/da/d54/group__imgproc__transform.html#ga69f2545a8b62a6b0fc2ee060dc30559d)

We should optimize this function. Some ideas:
- precomputing all the transformations; first image will cost, then next images can used precomputed values
- using std::thread and other c++11 features
- using SSE or OpenMP

Note that this function should work also if c++11 is disabled. In that case we could admit to use the existing code

**Comment by yshkp** [comment]
@fspindle I read about both functions `vpImageTools::undistort()` and `cv::undistort()` and `vpImageTools::undistort()` requires upgradation in distortion parameter K<sub>d</sub> . Working on distortion coefficients computation.
