### ISSUE TITLE
Gaussian blur for color images

### ISSUE THREAD

**Issue by yshkp** [lagadic/visp#512]
Tutorial about implementing `vpImageFilter::gaussianBlur()` on RGB color images must be introduced.Extending it may be by introducing simultaneous grabbing image using color camera.

**Comment by yshkp** [comment]
@fspindle I would like you to have a view and give a brief so that I can start working on it. Also I would like to hear your suggestions.

**Comment by fspindle** [comment]
@yshkp Let's go on

**Comment by fspindle** [comment]
@yshkp Step by step. Sart with gaussianBlur() and functions that are called inside.

**Comment by yshkp** [comment]
@fspindle Please look into my doubt mentioned in previous comment.Do I need to create a test for it?

**Comment by yshkp** [comment]
@fspindle Please look into my doubt mentioned in previous comment.Do I also need to create a test for it?
