### ISSUE TITLE
Issue computing condition number on non-square matrices

### ISSUE THREAD

**Issue by romainla** [lagadic/visp#517]
Hello,

I noticed a possible issue for the computation of the condition number of non-square matrices.
The vpMatrix::cond()const function calls vpMatrix::svd(vpColVector&, vpMatrix&) to compute the condition number. The possible issue comes from the fact that the svd function which will actually be called by the svd function depends on the library installed on the computer and that they do not have the same behavior when dealing with non-square matrices.
To this message should be attached an archive with a small testing program. The cond function has been reimplementing for each available algorithm. The results are the same when the input matrix is square but not when the input matrix is non-square:
- With condLapack, the condition number of the non-square matrix is infinite.
- With condGsl, the program throws a gsl_error (handled by overwriting the gsl_error_handler).
- With condEigen3, the condition number is nan.
- With openCV, the condition number is equal to the result I got using Matlab.

The difference in the results comes from the fact that the svd function pads the singular value vector with 0s in the case of Lapack and Eigen3 implementations in the case of non-square matrices. In the contrary, the openCV implementation returns a singular value vector whose size is equal to the maximum reachable rank of the non-square matrix.

One last thing, the iteration condition in the current implementation of the cond function is i<M.getColumns(). Maybe it would be reasonable to iterate on the size of the singular value vector instead ?
[ConditionNumber.tar.gz](https://github.com/lagadic/visp/files/2787252/ConditionNumber.tar.gz)

I hope this message could be of some help.
I'm looking forward to exchange on this subject.

Regards,
Romain

**Comment by fspindle** [comment]
Fixed in PR #520
