### ISSUE TITLE
Issue computing matrix euclidean norm

### ISSUE THREAD

**Issue by romainla** [lagadic/visp#518]
Hello,

I noticed that there might be an issue for the computation of the euclidean norm of a matrix.

Here is the example program I used:
[MatrixEuclideanNorm.zip](https://github.com/lagadic/visp/files/2787384/MatrixEuclideanNorm.zip)

The euclidean norm of the identity matrix should be one. Its inverse and its pseudo-inverse should be the identity matrix and their euclidean norm should also be equal to one.
However, in both case the result of the call to euclideanNorm gave sqrt(3) for the 3*3 identity matrix, instead of 1.

I found at this adress a way of computing the Euclidean norm of a matrix: https://en.wikipedia.org/wiki/Matrix_norm

> In the special case of p = 2 (the Euclidean norm or ℓ2-norm for vectors), the induced matrix norm is the spectral norm. The spectral norm of a matrix A is the largest singular value of A i.e. the square root of the largest eigenvalue of the positive-semidefinite matrix A ∗ A^{*}

If it seems correct to you, I could propose a pull request with the corresponding changes.

Regards,
Romain

**Comment by fspindle** [comment]
Fixed in PR #520
