### ISSUE TITLE
An Error during making 'tutorial-mb-generic-tracker-apriltag-live-webcam'

### ISSUE THREAD

**Issue by KIMJINU** [lagadic/visp#531]
Hello. I got the following error when trying to make 'tutorial-mb-generic-tracker-apriltag-live-webcam' of Visp example using Ubuntu in VirtualBox. I'd appreciate it if you could tell me what that error means and how to fix it.

/home/jinu/visp-ws/generic-apriltag/tutorial-mb-generic-tracker-apriltag-live-webcam.cpp: In function ‘state_t track(const vpImage<unsigned char>&, vpMbGenericTracker&, double, vpHomogeneousMatrix&)’:
/home/jinu/visp-ws/generic-apriltag/tutorial-mb-generic-tracker-apriltag-live-webcam.cpp:98:37: error: ‘class vpMbGenericTracker’ has no member named ‘computeCurrentProjectionError’; did you mean ‘computeProjectionError’?
   double projection_error = tracker.computeCurrentProjectionError(I, cMo, cam);
                                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                     computeProjectionError
CMakeFiles/tutorial-mb-generic-tracker-apriltag-live-webcam.dir/build.make:62: recipe for target 'CMakeFiles/tutorial-mb-generic-tracker-apriltag-live-webcam.dir/tutorial-mb-generic-tracker-apriltag-live-webcam.cpp.o' failed
make[3]: *** [CMakeFiles/tutorial-mb-generic-tracker-apriltag-live-webcam.dir/tutorial-mb-generic-tracker-apriltag-live-webcam.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/tutorial-mb-generic-tracker-apriltag-live-webcam.dir/all' failed
make[2]: *** [CMakeFiles/tutorial-mb-generic-tracker-apriltag-live-webcam.dir/all] Error 2
CMakeFiles/Makefile2:79: recipe for target 'CMakeFiles/tutorial-mb-generic-tracker-apriltag-live-webcam.dir/rule' failed
make[1]: *** [CMakeFiles/tutorial-mb-generic-tracker-apriltag-live-webcam.dir/rule] Error 2
Makefile:118: recipe for target 'tutorial-mb-generic-tracker-apriltag-live-webcam' failed
make: *** [tutorial-mb-generic-tracker-apriltag-live-webcam] Error 2

**Comment by fspindle** [comment]
It sounds that you don't use the latest VISP 3.2.0 release
