### ISSUE TITLE
Apriltag id not available in Android / Java wrapper

### ISSUE THREAD

**Issue by jukindle** [lagadic/visp#538]
The c++-way of reading the tag-id is parsing the message from the detector. There is however no function in the Java wrapper which returns this message. If I am wrong, could somebody tell me how to get the apriltag ids corresponding to the HomogeneousMatrices?

**Comment by s-trinh** [comment]
To get the tag-id, I see two options:

- add a method in `vpDetectorAprilTag` that returns a vector of int for the tag-id
- wrap the method to be available in Java [here](https://github.com/lagadic/visp/blob/44e5e1fd8e94e15c1c5bb2e0bc882478f27afcff/modules/java/misc/detection/gen_dict.json)

or use JNI to call C++ code from Java, something similar to [this](https://github.com/AKS1996/GSOC-Prep/blob/cb3f297a55044115eb060f173e1f47db48861ea4/visp-android-demos/VispAndroidDemoApp/app/src/main/cpp/native-lib.cpp)

A pull request will be appreciated if you implement and wrap a method that returns the tag-id for Java.

**Comment by bigcmos** [comment]
Do you have a how to get started building the Android app?

**Comment by fspindle** [comment]
Do you have seen this [project](https://github.com/AKS1996/GSOC-Prep/tree/master/visp-android-demos/AprilTagDetection) ?

[Here](https://github.com/AKS1996/GSOC-Prep) are also a set of java and android examples.
