### ISSUE TITLE
AprilTag detector freeze with msvc built when more than 1 thread is used

### ISSUE THREAD

**Issue by fspindle** [lagadic/visp#559]
This issue occurs on Windows with msvc14 and msvc15 when `3rdparty/pthreads-win32` is used.

It could be reproduced running:
````
tutorial-apriltag-detector --nthreads 2
````

**Comment by s-trinh** [comment]
If I remember correctly, I think that the issue is not present anymore when pthreads is built in shared library.

**Comment by fspindle** [comment]
Not checked recently, but from what I remmember you are right. Note that the libraries in 3rdparty folder should be built as static libs.

**Comment by fspindle** [comment]
To keep a trace after some tests:
- the freeze doesn't occurs with MinGW that uses native pthread library
- the freeze occurs with msvc when pthread built-in is used.
- To reproduce the issue run:
    ```
    tutorial-apriltag-detector.exe --nthreads 2
    ```
- It hangs in `workerpool.c` [L188](https://github.com/lagadic/visp/blob/master/3rdparty/apriltag/common/workerpool.c#L188) that calls `pthread_cond_wait(&wp->startcond, &wp->mutex)`
