### ISSUE TITLE
vpImage.h SegmentationFault, if bitmap is not copied

### ISSUE THREAD

**Issue by adamp87** [lagadic/visp#596]
Using constructor vpImage with copyData=false, the destructors still deallocates the pointer bitmap. This seems like a bug, since vpImage has no ownership ower the memory for the image. It also results in AccessViolation.

Sample code for testing:
`int main()
{
	{
		cv::Mat img = cv::imread("img.png");
		cv::cvtColor(img, img, cv::COLOR_RGB2GRAY);
		{
			vpImage<unsigned char> I(img.data, img.rows, img.cols, false);
		} // destructor calls delete[]bitmap
	} // crash, since img.data is already freed by vpImage
	return 0;
}`

Suggested simple solution to have a flag, indicating ownership. Later could be improved to a reference counter: 
[vpImage.zip](https://github.com/lagadic/visp/files/3315264/vpImage.zip)

**Comment by s-trinh** [comment]
Thanks for the report.
