### ISSUE TITLE
Issue with vpMath::round().

### ISSUE THREAD

**Issue by s-trinh** [lagadic/visp#6]
The function vpMath::round should round a double to the nearest integer but there are some differences with the round function in math.h.
For example the code:
```
vpMath::round(5.5)
vpMath::round(-5.5)
```
produces 5 and -5 but should produces 6 and -6 ([example code](https://ideone.com/VldhPc)).

**Comment by fspindle** [comment]
Fixed #6

**Comment by s-trinh** [comment]
##### Complementary information:
In fact, there are multiple [rounding methods](https://en.wikipedia.org/wiki/Rounding) for floating point numbers.
The rounding mode for round function in math.h is [round half away from zero](http://en.cppreference.com/w/c/numeric/math/round) whereas the default rounding mode used in IEEE 754 computing functions and operators is [round half to even](https://en.wikipedia.org/wiki/Rounding#Round_half_to_even).
The difference can be seen [here](https://en.wikipedia.org/wiki/Rounding#Round_half_to_odd).
