### ISSUE TITLE
Performance issues in vpTemplateTrackerMIInverseCompositional

### ISSUE THREAD

**Issue by artaran** [lagadic/visp#614]
Hello, 

The function **vpTemplateTrackerMIInverseCompositional::trackNoPyr()**    [dynamically allocates](https://github.com/lagadic/visp/blob/4efcc0b64b9911d676ed3c021d713e21dcfee3a0/modules/tracker/tt_mi/src/mi/vpTemplateTrackerMIInverseCompositional.cpp#L281) a very large number of small objects (2 * number of points * number of iterations) resulting in a significant performance penalty. Profiling the _templateTracker_ example configured to run that tracker shows that around 15% of the total time of the application (including display, ...) is due to these allocations and the tracking time can be significantly reduced by moving these two variables out of the inner loop.

Additionally, the stopping criteria of the optimization loop appear to be too strict for a tracking use case (as opposed to a physical positioning of a robot). For example, because the criterion _evalRMS_ is trying to perfectly align the triangle corners the number of iterations grows unreasonably large for no observable change. Plotting the residual over the iterations show that the most of the work is done in around 20 iterations but the tracker will still run 100s of iterations for some frames. 
I think loosening the thresholds (especially *threshold_RMS*) could significantly improve the runtime of that example without impacting the tracking accuracy.

The [vpTemplateTrackerMIForwardAdditional](https://github.com/lagadic/visp/blob/4efcc0b64b9911d676ed3c021d713e21dcfee3a0/modules/tracker/tt_mi/src/mi/vpTemplateTrackerMIForwardAdditional.cpp#L217) might have a similar issue with the number of the dynamic memory allocation but I did not profile that code. I also haven't checked beyond these two trackers.

**Comment by fspindle** [comment]
Thanks for your feadback. I will investigate these days...
