### ISSUE TITLE
SCALE_AUTO not a member of 'vpDisplay'

### ISSUE THREAD

**Issue by babindemers** [lagadic/visp#626]
Hi, I'm currently doing your tutorial on how to create and build a CMake project that uses ViSP on Unix or Windows. 
I'm not able to build the tutorial-viewer example, because I get this error:

error: ‘SCALE_AUTO’ is not a member of ‘vpDisplay’
     vpDisplayX d(I, vpDisplay::SCALE_AUTO);

I tried deleting the build folder and ude the cmake again, but it didn't help.

Thanks for any advice.

**Comment by fspindle** [comment]
`vpDisplay::SCALE_AUTO` was introduced in visp 3.1.0.
It sounds that you are using an older version

**Comment by babindemers** [comment]
Thanks, I deleted the packages and redownloaded ViSP from the source code.
