### ISSUE TITLE
Support for Aubo i5 robot

### ISSUE THREAD

**Issue by sebymv** [lagadic/visp#632]
I am new to visual servoing.I plan to use an intel realsense d435 camera and an Aubo i5 robot for visual servoing. I would like to know if there are any support files for Aubo i5 robots in Visp. How can I begin using the Visp platform with Aubo i5 robot?

**Comment by fspindle** [comment]
In ViSP there is support for realsense D435 camera, but not for Aubo i5 robot.

If you want to contribute, you can start the introduction of the Aubo i5 robot as a pull request. A good starting point would be to do something similar to this PR #625 which intend to introduce support for Jaco2 robot. I can than help you...
