### ISSUE TITLE
Difficulty to link with visp_ros

### ISSUE THREAD

**Issue by gchabert** [lagadic/visp#658]
I've installed visp_ros without any problem following [this tutorial](http://wiki.ros.org/visp_ros/Tutorials/Howto_install_visp_ros), but when I am trying to compile ``tutorial-ros-grabber.cpp`` as explained in [here](http://docs.ros.org/hydro/api/visp_ros/html/tutorial-ros-grabber.html#ros-grabber), I get the following error:

```
CMake Error at /home/gilles/catkin_ws/install/share/visp_ros/cmake/visp_rosConfig.cmake:150 (message):
  Project 'tutorial-ros-grabber' tried to find library
  'libvisp_ros_bebop2_visual_servo_nodelet'.  The library is neither a target
  nor built/installed properly. 
```

Can you help me? I'm using ros melodic under Ubuntu 18.

Sorry, I don't know much about cmake.

**Comment by fspindle** [comment]
Try upgrading visp_ros

```
cd /home/gilles/catkin_ws/src/visp_ros
git pull
cd ..
catkin_make
```

**Comment by gchabert** [comment]
It says 'Already up to date'

**Comment by fspindle** [comment]
Which version of ViSP are you using ? and how do you install it ?

**Comment by gchabert** [comment]
I first installed visp 3.2 on my system using ``apt-get install ros-melodic-visp`` (I read the version number in ``package.xml``).
Then I installed visp_ros 1.0.0 in my catkin workspace as explained [here](http://wiki.ros.org/visp_ros/Tutorials/Howto_install_visp_ros).

**Comment by fspindle** [comment]
Fixed. Do a `git pull` in visp_ros folder.

**Comment by gchabert** [comment]
Thanks Fabien
