### ISSUE TITLE
vpMbEdgeTracker.h did not have setDisplayMovingEdges in  Visp 3.2.1

### ISSUE THREAD

**Issue by DavidLeeDoosan** [lagadic/visp#676]
I have a question about setDisplayMovingEdges  of vpMbEdgeTracker.h in Visp 2.9.0.

I can not use  setDisplayMovingEdges  of vpMbEdgeTracker.h in Visp 3.2.1.

I checked that vpMbEdgeTracker.h did not have setDisplayMovingEdges in  Visp 3.2.1.

How can I use setDisplayMovingEdges  of vpMbEdgeTracker.h in Visp 3.2.1?

**Comment by fspindle** [comment]
`setDisplayMovingEdge()` was marked [deprecated](https://visp-doc.inria.fr/doxygen/visp-2.10.0/classvpMbEdgeTracker.html#a953e1bfd6deece99864c72b50116bb22) in ViSP 2.10.0 and removed in 3.0.0. The doc says that you have to use `vpMbTracker::setDisplayFeatures()` instead.

Replacing `setDisplayMovingEdge()` by `setDisplayFeatures()` should fix the build issue.
