### ISSUE TITLE
Build fails: error: PCL requires C++14 or above

### ISSUE THREAD

**Issue by yurivict** [lagadic/visp#690]
http://beefy6.nyi.freebsd.org/data/120amd64-default/523997/logs/visp-3.2.0_7.log

You set ```-std=c++11``` but then you include the code that requires C++14.
You need to set ```-std=c++14``` too.

**Comment by fspindle** [comment]
Thanks for your effort to package ViSP for FreeBSD.
This is already fixed in the current version that will be released soon.
Can you wait the next release, I hope that it will be ready around February 15 ?

**Comment by yurivict** [comment]
Yes, I will wait, no problem!

Thank you,
Yuri

**Comment by fspindle** [comment]
@yurivict The new release is out. It fixes this issue. Thanks in advance for packaging ViSP for FreeBSD.

**Comment by yurivict** [comment]
I've updated the FreeBSD port, thanks!
