### ISSUE TITLE
Unable to display an image

### ISSUE THREAD

**Issue by Zumbalamambo** [lagadic/visp#691]
I tried to run the following code ,

```
/tmp/ccEOqQAp.o: In function `main':
blob.cpp:(.text+0x401): undefined reference to `vpDisplayX::vpDisplayX()'
blob.cpp:(.text+0x470): undefined reference to `vpDisplayX::init(vpImage<unsigned char>&, int, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
blob.cpp:(.text+0x4ac): undefined reference to `vpDisplayX::~vpDisplayX()'
blob.cpp:(.text+0x50b): undefined reference to `vpDisplayX::~vpDisplayX()'
/tmp/ccEOqQAp.o: In function `vpException::~vpException()':
blob.cpp:(.text._ZN11vpExceptionD2Ev[_ZN11vpExceptionD5Ev]+0xf): undefined reference to `vtable for vpException'
/tmp/ccEOqQAp.o: In function `vpImage<unsigned char>::init(unsigned int, unsigned int)':
blob.cpp:(.text._ZN7vpImageIhE4initEjj[_ZN7vpImageIhE4initEjj]+0x169): undefined reference to `vpException::vpException(int, char const*, ...)'
blob.cpp:(.text._ZN7vpImageIhE4initEjj[_ZN7vpImageIhE4initEjj]+0x177): undefined reference to `typeinfo for vpException'
blob.cpp:(.text._ZN7vpImageIhE4initEjj[_ZN7vpImageIhE4initEjj]+0x1f5): undefined reference to `vpException::vpException(int, char const*, ...)'
blob.cpp:(.text._ZN7vpImageIhE4initEjj[_ZN7vpImageIhE4initEjj]+0x203): undefined reference to `typeinfo for vpException'
collect2: error: ld returned 1 exit status
```

I ran it as `g++ blob.cpp`

> /tmp/ccEOqQAp.o: In function `main':
> blob.cpp:(.text+0x401): undefined reference to `vpDisplayX::vpDisplayX()'
> blob.cpp:(.text+0x470): undefined reference to `vpDisplayX::init(vpImage<unsigned char>&, int, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
> blob.cpp:(.text+0x4ac): undefined reference to `vpDisplayX::~vpDisplayX()'
> blob.cpp:(.text+0x50b): undefined reference to `vpDisplayX::~vpDisplayX()'
> /tmp/ccEOqQAp.o: In function `vpException::~vpException()':
> blob.cpp:(.text._ZN11vpExceptionD2Ev[_ZN11vpExceptionD5Ev]+0xf): undefined reference to `vtable for vpException'
> /tmp/ccEOqQAp.o: In function `vpImage<unsigned char>::init(unsigned int, unsigned int)':
> blob.cpp:(.text._ZN7vpImageIhE4initEjj[_ZN7vpImageIhE4initEjj]+0x169): undefined reference to `vpException::vpException(int, char const*, ...)'
> blob.cpp:(.text._ZN7vpImageIhE4initEjj[_ZN7vpImageIhE4initEjj]+0x177): undefined reference to `typeinfo for vpException'
> blob.cpp:(.text._ZN7vpImageIhE4initEjj[_ZN7vpImageIhE4initEjj]+0x1f5): undefined reference to `vpException::vpException(int, char const*, ...)'
> blob.cpp:(.text._ZN7vpImageIhE4initEjj[_ZN7vpImageIhE4initEjj]+0x203): undefined reference to `typeinfo for vpException'
> collect2: error: ld returned 1 exit status
> 

I have of course installed visp. How do I fix this?

**Comment by fspindle** [comment]
Use CMake to detect ViSP headers and libraries as explained in getting started [tutorial](https://visp-doc.inria.fr/doxygen/visp-daily/tutorial-getting-started.html)
