### ISSUE TITLE
3.3.0 build fails on non-linux systems: fatal error: 'linux/serial.h' file not found

### ISSUE THREAD

**Issue by yurivict** [lagadic/visp#713]
```
--- 3rdparty/qbdevice/CMakeFiles/visp_qbdevice.dir/all ---
/wrkdirs/usr/ports/misc/visp/work/visp-3.3.0/3rdparty/qbdevice/qbmove_communications.cpp:68:14: fatal error: 'linux/serial.h' file not found
    #include <linux/serial.h>
             ^~~~~~~~~~~~~~~~
1 error generated.
```

FreeBSD 12.

**Comment by fspindle** [comment]
Can you update the locate database to see where the `linux.h` header is:

```
# /usr/libexec/locate.updatedb
# locate serial.h
```

**Comment by yurivict** [comment]
FreeBSD doesn't have the ```linux.h``` header.

**Comment by fspindle** [comment]
Does ViSP build if you comment the line in `qbmove_communication.cpp`?

**Comment by yurivict** [comment]
> Does ViSP build if you comment the line in qbmove_communication.cpp?

No, because there are several constants that are defined in linux.h.

**Comment by fspindle** [comment]
OK, I need to install a FreeBSD VM to investigate on my side.

In the mean time, a quick fix is to configure ViSP with -DWITH_QBDEVICE=OFF cmake option

**Comment by yurivict** [comment]
I used ```-DWITH_QBDEVICE=OFF```, thanks.
