### ISSUE TITLE
Static variable in vpServo

### ISSUE THREAD

**Issue by s-trinh** [lagadic/visp#785]
I was looking quickly into the source code of the `vpServo` class.

I believe static variable should be avoided here (and in similar locations in the file): https://github.com/lagadic/visp/blob/9498e01b62ed1c1adc5d7f6d47ae995d89d0ec46/modules/vs/src/vpServo.cpp#L1083

Instead, a member variable looks more appropriate I think. And it can be initialized in the constructor and here: https://github.com/lagadic/visp/blob/9498e01b62ed1c1adc5d7f6d47ae995d89d0ec46/modules/vs/src/vpServo.cpp#L141

Otherwise, two `vpServo` objects will share the same `iteration` count. Quick code for testing [here](http://cpp.sh/7axc4).
Looking quickly at the code, this variable is not really useful since it is used for this: https://github.com/lagadic/visp/blob/9498e01b62ed1c1adc5d7f6d47ae995d89d0ec46/modules/vs/src/vpServo.cpp#L1244-L1251

and this: https://github.com/lagadic/visp/blob/9498e01b62ed1c1adc5d7f6d47ae995d89d0ec46/modules/vs/src/vpServo.cpp#L1181-L1185

So no bug in the code.

---

As a side note, I am wondering why `kill()` method is not called directly in the `vpServo` destructor? https://github.com/lagadic/visp/blob/9498e01b62ed1c1adc5d7f6d47ae995d89d0ec46/modules/vs/src/vpServo.cpp#L116-L125

I did not look carefully in the source code. So maybe there is a valid reason, but just in case.

**Comment by fspindle** [comment]
I don't see any good reason why `kill()` was not called by the destructor. Maybe that this was required at the beginning, a long time ago, but I don't remember. Calling `kill()` in the destructor doesn't produce memory leaks.
