### ISSUE TITLE
Formula rendering in online doc

### ISSUE THREAD

**Issue by s-trinh** [lagadic/visp#796]
Maybe related: https://github.com/lagadic/visp/commit/1e9d97d5d16c9ec6e1d59afa447890aa57f1e853

In the current doc, for [instance](https://visp-doc.inria.fr/doxygen/visp-daily/classvpFeatureDepth.html), on my computer I have:

![image](https://user-images.githubusercontent.com/8035162/88239452-ba34e700-cc84-11ea-9c14-1633cccf7d2e.png)

[Previous doc](https://visp-doc.inria.fr/doxygen/visp-3.3.0/classvpFeatureDepth.html) shows correct formula rendering.

**Comment by fspindle** [comment]
Fixed in PR #813
