### ISSUE TITLE
Commit 26773587 breaks API compatibility

### ISSUE THREAD

**Issue by pgchatela** [lagadic/visp#873]
In vpRealSense2, the type of protected members m_pipe and m_pipelineProfile is modified, and protected member m_init is removed, so subclasses using these members will be broken.

**Comment by fspindle** [comment]
okay, okay, you are right, keeping compat with previous versions is important.
Pointers were introduced to simplify `vpRealSense2::getDepthScale()` and `vpRealSense2::getProductLine()`.
