### ISSUE TITLE
how can i get eular angle?

### ISSUE THREAD

**Issue by jcyhcs** [lagadic/visp#911]
hi,professor:
when use  AprilTag marker detection, it can got apritag pose, but how can i get apriltag's eular angle?

please help!

**Comment by fspindle** [comment]
You didn't check a lot in the [doc](https://visp-doc.inria.fr/doxygen/visp-daily/index.html).

There are several euler representations, [vpRxyzVector](https://visp-doc.inria.fr/doxygen/visp-daily/classvpRxyzVector.html), [vpRzyzVector](https://visp-doc.inria.fr/doxygen/visp-daily/classvpRzyzVector.html)... that could be constructed from a rotation matrix

```
vpRxyzVector eular_rxyz( cMo.getRotationMatrix() );
```
