### ISSUE TITLE
Problem with surface rendering

### ISSUE THREAD

**Issue by DavidMazaud** [lagadic/visp#915]
Hi there,

I have started using Visp software but after doing "calculate dentisty", when I want to make a surface rendering, the software crashes and closes straight away.
It is the last version of Visp, 3.4.0. Any advice to help me on that?
Thanks  a lot
Best
David

**Comment by s-trinh** [comment]
Hi,

More information are needed such as:

- reproducible code
- link to the [documentation](http://visp.inria.fr/documentation/) for the faulty function
- ...
