### ISSUE TITLE
makeTempDirectory() for Windows

### ISSUE THREAD

**Issue by s-trinh** [lagadic/visp#948]
There is [makeTempDirectory()](https://visp-doc.inria.fr/doxygen/visp-3.3.0/classvpIoTools.html#ad2c58abadddb9550268ad6c81fcc62d9) but only for Unix right now.

Could be interesting to update it for Windows also. Maybe using a combination of?
- https://en.wikipedia.org/wiki/Temporary_folder
- [getenv()](https://visp-doc.inria.fr/doxygen/visp-3.3.0/classvpIoTools.html#aa1e1bd46aaedead314c61e3a4d6cde99)

**Comment by fspindle** [comment]
I found this [page](https://docs.microsoft.com/en-us/windows/win32/fileio/creating-and-using-a-temporary-file) that may help
